/**
 * Processes a single simulation tick for the Random component
 *
 * Returns the current random output value generated by this component. The Random
 * component generates new values at specified intervals based on its configuration,
 * and this function returns the most recently generated value during simulation.
 *
 * @param {Object} component - The Random component to process
 * @param {string} component.id - The unique identifier of the component
 * @param {string} component.name - The component type name ('Random')
 * @param {number} component.currentOutput - The most recently generated random value
 * @param {Object} component.settings - The component's configuration settings
 * @param {number} component.settings.min - The minimum value for random generation
 * @param {number} component.settings.max - The maximum value for random generation
 * @param {number} component.settings.period - The time interval between value generations in milliseconds
 * @param {number} component.lastExecution - The timestamp of the last value generation
 * @returns {number} The current random output value that should be output by this component
 *
 * @description
 * This function is called during each simulation tick to determine the
 * output value of a Random component. The Random component generates new
 * values at specified intervals (controlled by the period setting), and
 * this function returns the most recently generated value.
 *
 * The actual value generation occurs in the main tick() function, which
 * updates the component's currentOutput property when the period has elapsed.
 * This function simply returns that pre-calculated value for signal propagation.
 *
 * The returned value will be propagated to any components connected
 * to this Random component's output pin.
 *
 * @example
 * // Process a Random component with current output value 42
 * const component = {
 *   id: 'random-1',
 *   name: 'Random',
 *   currentOutput: 42,
 *   settings: { min: 1, max: 100, period: 1000 },
 *   lastExecution: 1640995200000
 * }
 * const output = circuitStore._processRandomTick(component)
 * console.log(output) // 42
 */
export default function processRandomTick (component) {
  return { VALUE_OUT: component.currentOutput }
}
